window.LESSONS = [
  {
    id: 1,
    stage: 'Python 起步',
    title: '输出你的第一行 Python',
    intro: '先不背概念。让程序真的输出一句话，你就已经开始写 Python 了。',
    task: '让程序输出：Hello Python',
    concept: '<code>print()</code> 可以先理解为“把内容显示出来”。字符串需要放在引号里。',
    starter: "print('Hello Python')",
    stdin: '', expected: 'Hello Python',
    simpleExplain: '先只记住一件事：print() 就是“让 Python 把东西显示出来”。\n\n引号里的 Hello Python 是你想显示的文字。',
    codeExplain: '这一行由两部分组成：\n1. print(...)：执行“显示内容”的动作。\n2. \'Hello Python\'：一段字符串，也就是文字。\n\n整句可以读成：让 Python 显示 Hello Python。',
    hints: ['你需要使用 print()。', '把要输出的文字放进引号，再放进 print 的括号里。', "可以写成：print('Hello Python')"]
  },
  {
    id: 2,
    stage: 'Python 起步',
    title: '修改程序输出',
    intro: '程序不会猜你的意思，它只执行你写下来的内容。',
    task: '修改代码，让程序只输出：Hello 李永琪',
    concept: '这一关只改字符串内容，不增加新的语法。',
    starter: "print('Hello Python')",
    stdin: '', expected: 'Hello 李永琪',
    simpleExplain: '你不需要学新的语法。只需要把引号里的文字改成任务要求的内容。',
    codeExplain: 'print() 没变，变化的是括号里的字符串。代码编辑最基本的能力，就是知道“哪一部分控制了什么”。',
    hints: ['不需要增加新的函数。', '只修改 print() 里面的文字。', "目标可以写成：print('Hello 李永琪')"]
  },
  {
    id: 3,
    stage: '变量',
    title: '把名字存进变量',
    intro: '变量可以理解成一个带名字的小盒子，用来保存数据。',
    task: '创建变量 name = "李永琪"，然后用变量输出：Hello 李永琪',
    concept: '<code>name = "李永琪"</code> 表示把字符串保存到变量 name 中。',
    starter: "name = '李永琪'\n\n# 使用 name 变量完成输出\n",
    stdin: '', expected: 'Hello 李永琪', codeMustInclude: ['name'],
    simpleExplain: '把变量想成一个贴了标签的小盒子。name 是标签，“李永琪”是盒子里的内容。以后写 name，就相当于拿出里面的内容。',
    codeExplain: '第一行把字符串保存到 name。接下来应该把固定文字 Hello 和变量 name 一起交给 print()。',
    hints: ['第二部分需要用 print()。', 'print 可以同时接收多个值，例如 print("Hello", name)。', '试试：print("Hello", name)']
  },
  {
    id: 4,
    stage: '变量',
    title: '让 Python 帮你计算',
    intro: '变量不仅能保存文字，也能保存数字。',
    task: '已知 a = 12，b = 8，请输出它们的和 20。',
    concept: '数字不需要引号；<code>+</code> 可以做加法。',
    starter: 'a = 12\nb = 8\n\n# 在下面输出 a + b\n',
    stdin: '', expected: '20',
    simpleExplain: 'a 和 b 现在分别装着数字 12 和 8。写 a + b，Python 就会先把它们取出来再相加。',
    codeExplain: 'a = 12 和 b = 8 是赋值。a + b 是表达式。把表达式放进 print()，就能看到计算结果。',
    hints: ['先算 a + b。', '把计算表达式直接放进 print() 也可以。', '试试：print(a + b)']
  },
  {
    id: 5,
    stage: '输入',
    title: '让程序接收输入',
    intro: 'input() 能让程序读取用户输入。这里我们先从文字开始。',
    task: '读取一个名字，并输出：你好 张三。测试输入已经填好。',
    concept: '<code>input()</code> 返回字符串。你可以先把它保存到变量里。',
    starter: "name = input()\n\n# 输出：你好 张三\n",
    stdin: '张三', expected: '你好 张三',
    simpleExplain: 'input() 的作用是“等用户给程序一个内容”。这一关输入框已经放了“张三”，所以 name 会得到“张三”。',
    codeExplain: 'name = input() 会把一次输入保存到 name。然后你需要把“你好”和 name 一起输出。',
    hints: ['input() 得到的内容已经保存在 name 中。', '可以让 print 同时输出固定文字和变量。', '试试：print("你好", name)']
  },
  {
    id: 6,
    stage: '条件判断',
    title: '第一次 if 判断',
    intro: '程序开始“做决定”了。条件成立时，才执行缩进后的代码。',
    task: 'score = 85。当 score >= 60 时输出：及格',
    concept: 'Python 的 if 后面要写冒号 <code>:</code>，代码块需要缩进。',
    starter: 'score = 85\n\n# 写一个 if 判断\n',
    stdin: '', expected: '及格',
    simpleExplain: 'if 就是“如果”。可以读成：如果 score 大于等于 60，就执行下面缩进的代码。',
    codeExplain: 'if 后面放条件；冒号表示下面要开始一个代码块；缩进表示这行代码属于这个 if。',
    hints: ['条件可以写成 score >= 60。', 'if 行末尾不要忘记冒号，下一行要缩进。', '示例：\nif score >= 60:\n    print("及格")']
  },
  {
    id: 7,
    stage: '循环',
    title: '让代码重复执行',
    intro: '循环的价值是：同一件事情不用手写很多遍。',
    task: '使用 for 循环依次输出 1、2、3，每个数字单独一行。',
    concept: '<code>range(1, 4)</code> 会产生 1、2、3，不包含 4。',
    starter: '# 使用 for 和 range 完成任务\n',
    stdin: '', expected: '1\n2\n3',
    simpleExplain: 'for 可以理解成“对一组东西，一个一个做同一件事”。range(1, 4) 会给出 1、2、3。',
    codeExplain: 'for i in range(1, 4) 表示让 i 依次取得 1、2、3。缩进的 print(i) 每次都会执行一次。',
    hints: ['你可以遍历 range(1, 4)。', '循环体里的 print 需要缩进。', '示例：\nfor i in range(1, 4):\n    print(i)']
  },
  {
    id: 8,
    stage: '循环',
    title: '理解 range 的边界',
    intro: '这是初学者非常容易犯错的地方：range 的结束值通常不包含在结果里。',
    task: '使用 range，让程序依次输出 2、3、4、5。',
    concept: '想输出到 5，range 的结束参数通常要写成 6。',
    starter: 'for i in range(2, ?):\n    print(i)\n',
    stdin: '', expected: '2\n3\n4\n5',
    prediction: {
      question: '如果代码是 range(2, 6)，最后一次循环时 i 是多少？',
      options: ['4', '5', '6'],
      answer: '5',
      success: '对。range(2, 6) 包含 2、3、4、5，但不包含 6。',
      fail: '先别急着记答案：range 的 stop 参数本身不会被包含。'
    },
    simpleExplain: 'range(开始, 结束) 里的“结束”通常不会出现。所以如果你希望最后输出 5，结束值要再往后写一个数。',
    codeExplain: '现在的 ? 是故意留下的空位。你需要决定 stop 应该写什么，让 range 从 2 走到 5，但不多走一步。',
    hints: ['range(start, stop) 不包含 stop。', '如果最后一个数字要是 5，stop 应该比 5 大 1。', '把 ? 改成 6。']
  },
  {
    id: 9,
    stage: '列表',
    title: '一次保存多个数据',
    intro: '列表 list 可以保存一组有顺序的数据。',
    task: '给定 scores = [96.81, 97.24, 98.41]，输出其中最大值。',
    concept: '<code>max()</code> 可以返回列表中的最大值。',
    starter: 'scores = [96.81, 97.24, 98.41]\n\n# 输出最大值\n',
    stdin: '', expected: '98.41',
    simpleExplain: '列表就是把多个值装在同一个有顺序的容器里。这里 scores 里有三个实验结果。',
    codeExplain: 'scores 是一个列表。Python 内置的 max(scores) 会从里面找出最大值，然后可以用 print() 显示它。',
    hints: ['Python 已经有求最大值的内置函数。', '这个函数叫 max。', '试试：print(max(scores))']
  },
  {
    id: 10,
    stage: '列表 + 循环',
    title: '遍历一组数据',
    intro: '科研代码里你会经常看到“对一批数据逐个处理”。',
    task: '依次输出列表中的三个数据：96.81、97.24、98.41。',
    concept: 'for 可以直接遍历列表，不一定要使用下标。',
    starter: 'scores = [96.81, 97.24, 98.41]\n\n# 遍历 scores\n',
    stdin: '', expected: '96.81\n97.24\n98.41',
    simpleExplain: '这一关把“列表”和“循环”连起来：让一个变量逐个拿到列表里的每个值。',
    codeExplain: 'for score in scores 会让 score 依次变成三个分数。循环体里打印 score，就会每个值输出一次。',
    hints: ['可以写 for score in scores。', '循环体中打印 score。', '示例：\nfor score in scores:\n    print(score)']
  },
  {
    id: 11,
    stage: '函数',
    title: '写你的第一个函数',
    intro: '函数把一段逻辑打包起来，可以反复调用，是读懂大型项目的关键。',
    task: '完成 add(a, b) 函数，让 print(add(3, 5)) 输出 8。',
    concept: '<code>return</code> 用来把函数计算得到的结果返回出去。',
    starter: 'def add(a, b):\n    # 在这里返回 a + b\n    pass\n\nprint(add(3, 5))\n',
    stdin: '', expected: '8',
    simpleExplain: '函数可以理解成一台小机器：把 a、b 放进去，机器做计算，再把结果送出来。return 就是“把结果送出来”。',
    codeExplain: 'def add(a, b) 定义函数；a、b 是参数；return 决定函数最后交回什么结果；add(3, 5) 是实际调用。',
    hints: ['函数里面需要返回一个结果。', '用 return，而不是只写 a + b。', '把 pass 改成：return a + b']
  },
  {
    id: 12,
    stage: 'Bug 修理厂',
    title: '找出隐藏的逻辑 Bug',
    intro: '现实中的代码很多时候不是让你从零写，而是让你找出哪里不对。',
    task: '下面程序本来应该输出 15，但现在输出 5。只修改必要的一行，让它输出 15。',
    concept: '循环中每次是“覆盖” total，还是“累加” total？这两个操作完全不同。',
    starter: 'numbers = [1, 2, 3, 4, 5]\ntotal = 0\n\nfor n in numbers:\n    total = n\n\nprint(total)\n',
    stdin: '', expected: '15',
    simpleExplain: '现在每次循环都把 total 直接改成当前 n，所以最后只剩下 5。真正需要的是“在原来的 total 上继续加”。',
    codeExplain: 'total = n 是覆盖；total += n 是累加。调试时要问：这行代码是在替换旧值，还是在旧值基础上更新？',
    hints: ['问题就在循环体里的 total = n。', '你需要把新的 n 加到已有 total 上。', '把 total = n 改成 total += n。']
  }
];
