addEngineeringStage(1, [
  {
    "title": "让程序真正输出内容",
    "task": "让程序只输出：Hello Engineer",
    "concept": "print() 与字符串字面量",
    "starter": "# 在下面写第一行 Python\n",
    "solution": "print('Hello Engineer')",
    "expected": "Hello Engineer",
    "why": "print() 负责把值写到标准输出；引号里的内容是字符串。",
    "walk": "Python 先创建字符串 Hello Engineer，再把它交给 print()，最后终端显示这段文字。",
    "hint1": "需要使用 print()。",
    "hint2": "文字要放在引号里。",
    "takeaway": "print() 是最基础的输出工具；字符串必须用引号包住。"
  },
  {
    "title": "给数据起一个名字",
    "task": "创建变量 project = 'PyPath'，然后输出 PyPath。",
    "concept": "变量与赋值",
    "starter": "# 创建 project 变量并输出它\n",
    "solution": "project = 'PyPath'\nprint(project)",
    "expected": "PyPath",
    "why": "赋值语句把右边的值保存到左边的变量名中，后续通过变量名读取。",
    "walk": "先把字符串 PyPath 保存到 project；执行 print(project) 时再读取这个值。",
    "hint1": "先写 project = ...。",
    "hint2": "print 里应该放变量名，不要再写固定答案。",
    "takeaway": "变量是数据的名字，不是数据本身。"
  },
  {
    "title": "认识整数类型",
    "task": "创建 n = 42，并输出 type(n).__name__，目标输出：int",
    "concept": "整数 int 与 type()",
    "starter": "n = 42\n\n# 输出 n 的类型名称\n",
    "solution": "n = 42\nprint(type(n).__name__)",
    "expected": "int",
    "why": "没有小数点的 42 是整数；type() 可以查看对象类型。",
    "walk": "n 指向整数对象 42；type(n) 得到 int 类型对象；.__name__ 得到字符串 int。",
    "hint1": "使用 type(n)。",
    "hint2": "类型对象的 __name__ 可以得到名字。",
    "takeaway": "Python 中值有类型；变量名本身没有固定类型。"
  },
  {
    "title": "让表达式替你计算",
    "task": "已知 a = 7，b = 6，输出它们的乘积 42。",
    "concept": "数值表达式与 * 运算符",
    "starter": "a = 7\nb = 6\n\n# 输出乘积\n",
    "solution": "a = 7\nb = 6\nprint(a * b)",
    "expected": "42",
    "why": "表达式 a * b 会先读取两个变量，再进行乘法计算。",
    "walk": "a 取值 7，b 取值 6，乘法得到 42，print 再显示结果。",
    "hint1": "乘法运算符是 *。",
    "hint2": "可以直接把表达式放进 print()。",
    "takeaway": "print 可以接收计算表达式，而不只是固定文字。"
  },
  {
    "title": "在旧值基础上更新变量",
    "task": "count 初始为 2，再增加 3，最后输出 5。",
    "concept": "增强赋值 +=",
    "starter": "count = 2\n\n# 让 count 增加 3\n\nprint(count)\n",
    "solution": "count = 2\ncount += 3\nprint(count)",
    "expected": "5",
    "why": "count += 3 等价于 count = count + 3，但更适合表达“基于旧值更新”。",
    "walk": "count 从 2 开始；+= 读取旧值 2，加 3，再把 5 保存回 count。",
    "hint1": "不要直接把 count 改成 5。",
    "hint2": "使用 += 3。",
    "takeaway": "累加器的核心是基于旧值更新，而不是覆盖。"
  },
  {
    "title": "理解运算优先级",
    "task": "计算 (2 + 3) * 4，并输出 20。",
    "concept": "括号与运算优先级",
    "starter": "# 用一个表达式得到 20\n",
    "solution": "print((2 + 3) * 4)",
    "expected": "20",
    "why": "括号会让加法先执行，再进行乘法，避免依赖默认优先级造成误解。",
    "walk": "先计算括号内 2+3 得到 5，再计算 5*4 得到 20。",
    "hint1": "先让 2 + 3 执行。",
    "hint2": "使用括号明确顺序。",
    "takeaway": "工程代码里优先使用清楚的括号表达意图。"
  },
  {
    "title": "一次给多个变量赋值",
    "task": "使用一行代码让 x = 3、y = 5，然后输出 8。",
    "concept": "多变量赋值与解包",
    "starter": "# 一行给 x 和 y 赋值\n\nprint(x + y)\n",
    "solution": "x, y = 3, 5\nprint(x + y)",
    "expected": "8",
    "why": "Python 可以把右侧多个值按位置解包到左侧多个变量。",
    "walk": "右侧先形成两个值 3 和 5，再分别绑定到 x、y；最后求和。",
    "hint1": "左边可以写 x, y。",
    "hint2": "右边按同样顺序写 3, 5。",
    "takeaway": "解包要求左右数量对应，并按位置匹配。"
  },
  {
    "title": "布尔值不是字符串",
    "task": "创建 is_ready = True，并输出 True。",
    "concept": "布尔类型 bool",
    "starter": "# 创建布尔变量 is_ready\n\nprint(is_ready)\n",
    "solution": "is_ready = True\nprint(is_ready)",
    "expected": "True",
    "why": "True 和 False 是 Python 的布尔值，不需要也不应该加引号。",
    "walk": "变量保存布尔值 True；print 按布尔值的文本形式输出 True。",
    "hint1": "Python 的真值写作 True。",
    "hint2": "True 首字母要大写，并且不要加引号。",
    "takeaway": "True 与 'True' 类型不同：一个是 bool，一个是 str。"
  },
  {
    "title": "认识 None",
    "task": "令 result = None，输出 result is None 的结果。",
    "concept": "None 与身份判断 is",
    "starter": "result = None\n\n# 判断 result 是否为 None\n",
    "solution": "result = None\nprint(result is None)",
    "expected": "True",
    "why": "None 表示“没有值”；判断是否为 None 通常使用 is None。",
    "walk": "result 指向唯一的 None 对象；身份判断成立，因此得到 True。",
    "hint1": "不要和字符串 'None' 比较。",
    "hint2": "使用 is None。",
    "takeaway": "None 不是空字符串、0 或 False，它是独立的空值对象。"
  },
  {
    "title": "使用清晰的变量命名",
    "task": "创建变量 user_score = 88，并输出它。",
    "concept": "snake_case 命名",
    "starter": "# 使用 snake_case 创建变量\n",
    "solution": "user_score = 88\nprint(user_score)",
    "expected": "88",
    "why": "Python 工程代码通常用 snake_case 命名普通变量，让含义一眼可读。",
    "walk": "变量名 user_score 同时表达“用户”和“分数”，再通过 print 读取它。",
    "hint1": "变量名由 user 和 score 组成。",
    "hint2": "用下划线连接两个单词。",
    "takeaway": "好命名不是装饰，它直接降低维护代码的成本。"
  },
  {
    "title": "修复覆盖变量的 Bug",
    "task": "下面代码本来要输出 15，但错误地输出 5。只修改 total 更新那一行。",
    "concept": "覆盖赋值与累加的区别",
    "starter": "numbers = [1, 2, 3, 4, 5]\ntotal = 0\nfor n in numbers:\n    total = n\nprint(total)\n",
    "solution": "numbers = [1, 2, 3, 4, 5]\ntotal = 0\nfor n in numbers:\n    total += n\nprint(total)",
    "expected": "15",
    "why": "total = n 每次都会丢掉旧值；total += n 才是在旧结果上继续累计。",
    "walk": "total 按 0→1→3→6→10→15 变化，最后输出 15。",
    "hint1": "问题在循环里的赋值语句。",
    "hint2": "需要在旧 total 上继续加。",
    "takeaway": "调试状态变量时，要持续跟踪每次更新前后的值。"
  },
  {
    "title": "基础信息卡",
    "boss": true,
    "task": "已知 name='Ada'、years=2、projects=3。计算明年的 years，并输出三行：Name: Ada、Next year: 3、Projects: 3",
    "concept": "变量、表达式、输出与清晰命名的综合使用",
    "starter": "name = 'Ada'\nyears = 2\nprojects = 3\n\n# 完成三行输出\n",
    "solution": "name = 'Ada'\nyears = 2\nprojects = 3\nprint('Name:', name)\nprint('Next year:', years + 1)\nprint('Projects:', projects)",
    "expected": "Name: Ada\nNext year: 3\nProjects: 3",
    "must": [
      "name",
      "years",
      "projects"
    ],
    "why": "BOSS 关要求你自己决定哪些值直接输出、哪些值需要先做表达式计算。",
    "walk": "先保留三份基础数据；第二行使用 years + 1 得到 3；三次 print 分别形成三行输出。",
    "hint1": "第二行不是直接输出 years。",
    "hint2": "print 可以同时接收固定文字和变量。",
    "takeaway": "写程序时先分清“原始数据”“计算得到的数据”和“最终输出”。",
    "bossReview": "你已经完成变量、基本类型、表达式和状态更新的基础训练，可以开始处理来自用户的真实输入。"
  }
]);
